### ISSUE TITLE
Screenshots / Demo / Examples

### ISSUE THREAD

**Issue by yesoreyeram** [yesoreyeram/yesoreyeram-boomtheme-panel#1]
# Examples

![image](https://user-images.githubusercontent.com/153843/56890715-24ef7680-6a72-11e9-9978-64bb1b931335.png)
![image](https://user-images.githubusercontent.com/153843/56890722-2d47b180-6a72-11e9-8de0-078035674c31.png)

**Comment by yesoreyeram** [comment]
# Hello kitty

![image](https://user-images.githubusercontent.com/153843/56893470-a77c3400-6a7a-11e9-8c26-efae8d29b69e.png)

```
.navbar-page-btn {
  color: #eb5160;
}
.sidemenu-open .sidemenu,
.main-view {
  background: linear-gradient(45deg, blueviolet, crimson);
}
.navbar-button.active,
.navbar-button.disabled,
.navbar-button:active,
.navbar-button:focus,
.navbar-button:hover,
.navbar-button[disabled],
.navbar-button {
  background: #ffb8b7;
}
.panel-container {
  background: #ffb8b7;
  color: #eb5160;
  border-color: crimson;
  border-radius: 20px;
}

.theme-dark .react-grid-item > .react-resizable-handle:after {
  border: 0px;
}
p.panel-text-content {
  text-align: center;
}
.gicon-dashboard {
  background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAA+VBMVEX///8AAADmDmMAAwDoDmQABAD6+vr29vbe3t7v7+/Ozs7tDmbqDmXi4uLIyMijo6OFhYXp6em9vb2cnJytra12dnazs7PT09NoaGhYWFiQkJBdXV1lZWVJSUnExMR8fHwtLS2Li4svLy9BQUEgICCfn586OjodHR0SEhJPT08AAAZwcHAfHx8uLi7bD10lBA//0wIXBAozCReDDDdEBRuwDUxUCyXND1nBEFUrBRLcDVu4EE47CRueEUTeEWRpCS3BEll3CzKQDkCpEE3SrQlxYAvxywfiwQmBbxj/3QCghxNjVwwSBQljCyt7CzhOCSBaCyFMRBDBog1kCSjKAAAVc0lEQVR4nO1deXviONKPD8Bg7sMc4UwICU0PmYQQSAjJJj3vzM6+ne7d/f4fZq0q2ZZtGTC2IP08+f3RBzZYZZXqVunk5BOf+MQnPvGJj4t0pmyUc8ljD0MU0q2RhDgtB9+ldS96jXajuOGWj4qBxKLKuSNVb42dO/q5gw8xErQzyY1zzX1D2mheeW7R+D/1MZGX/GCmMWk0OTdIqeMNOCzK5nATZMyJh9tr8y9FUcw/B/RqfcIjz0TzqIMOgwwd8c+5LMvTxdst/X+PXCyfe+gajs6tj34VcZOG0SqJtZ6VVVlVs9m1AjMqtU7K7vXZLtTT5CupNvz37NhD3xEj4NHrRVa2oE9vJQXmi527Yob5UvMXmsQLMoHS96nsUGhO5QOSaKORd38LJ/78OEMOB8qjC1WVGQrV6fcEQ18r7fteCy78CkqxAQTOmQlELGwKhzz1f5KiK/VAKFUHtdqgUO3mUiGtSg0G+qp7CZT1uQSMyqfPRI98cRR56DuhdMoKhGaxvCvvpLTMKYhRH32y+qy/wu9Vgr5cPxybdiU/JkZpwzfSWv5icPqV3vtF+ubjUSAS9aJ/CVL0ydWCAIK8yHAIBDl3wSEylTNazb7nzgc/jzJLMXCpAZueiiSNjtlrEDMYV9lVqRm1Dve2NXcKZTkLfKoErWxi60mX4im0jcZRs9nxzo7JrqimtQrXdsYpfOYTKOvPEjFQg0QNSlPhCxFloXRlgKGfTOXKA48heVYsTL5KG/DmZlI1K+uyrssm3foLud4PejbYBMLNmgaO0iUO0vneJopsnOOXp96pW7zNZvNHQvcSiAhyBIF9RGvEEo617rtQLwbPW/+0V82TYeeJpnjSPfT9xLv+vdD1Jf6zaHB5kdh7wkVNBUZQ417L+5feZWdg1B3HtQZM6pIz+jdFotZMYrZ8so3TftE9k6lSJg8PvxJK38kJOjdBui9XZKg7G/jCaPD5QvUQaMEkNMGa302LxsxFm3GqRJJnyZlG8A0ppPGql+fIfPj2jUvKTE3haXr490+KRRv8A51+Yt+kq17OqAWaBHGgAM/obrolXe0NeOSdUIX2k12G+oyQ8yrr2QUwKJLp/OuMq1ANIbQh2pH4ZEC+PHNR+N3kzBfi60+vkaab2WqxWM5feJTZKMZJkxvw++19vw3KYs0uQ5l8Qham/lMhnPlzaVILgQ15ZgkgoDzx5enu7lahTIwRHRFA7/Vi36/DiloxFGYXZPBTFVwnk5RZ1pKz5kcruiLNeX399jiVzWvT5exGLKOi0e1XhjuiY82YjSmhwaRQfSKXfuiENJtEVP/K9UrWVQh5mPfp6htOraBkhwE/vslP2ggw71wWjW6qh8Sbrq7IXN15DHJ9TeY1sfBYCMsEG1yNGRArudz79XEovCdWzkp/JxOzdK1QMotPhEsX7o+Ro0VNIpifv+399aaPwuycCA/p/bspZh50j8+hqvOEedEX0iGvZYvK2htg+u4fKgFZunSP9sVSfV6Xg2BqKhPpRfdMorwQpzFgiPvHLIt+bUEnRPIzKVx8MslXXqbuWVT1RKRhbEJECsGmufdMVfYtkZB46w3IV8gMJ2bu72R/mh8OY6TLAXDp/skDcL2URw8Z6uMMZSaHwjvKwe+ua+AoK0LMU5A0EV7eJXe9ZSGOyJ3DB4uF3bbeO/lICIUYWd//pyvAjs+eKAba35x1CJ4HWm4Ke1X/ac75lZB8KWr8/bPNaPXducgjXn6CLLc3VfbQSLSFJL0uiMX6wrwWYidI/dioYpGPahMOkMRp1qbF9JtmmA6+9WkLHWy5paniFenavqoSW0+ROvGRxQCjNPwYxk5IXoKFnZhNdcRibWkLxWRT1xyq8pJ8em1SZCr+hEM/seaEeVA4mAg/oFmi4/p1Nnu9YzNq0u2zh09vqf6cmkzpzKGchZciKKqI9S2Z7TcGIk8nTHL9DUi86wyJqv5Crt7Iuj5TXNmqR3gvggozUJhOTtK12r4eRv1KsuMwFFfVEoRHlHtHzKpZUAnSz+mSUKqsbLtG/0E+FxVUxAyXRMazfwKBDchJVs0XTRbMTQ/QXI7Z7PLaucOk0PGs1Ed4O2IMb1NSMGmZ/d2XdLVDf2fYrlLtmgTXSlGuf8yXi9XbHcPAxMt3TFP9XYkoCzbDKeZRIv1OKlfPZDSW05PBqRzG9lZVDIsHZW+iw0kexv+MgpuuhPQ+fZzPZm8QxbAonEKgRmRNhpVPGwrwsdOuBE9iTeJS2azuMklRfYpahQQV+nwx6ihdGNkUmvrBZ6nqNI4qMGBK05TSWNwDMt08SNvv3iycOaEzi3yRZYr4BMG1nlDs4fWVTWfZFrDiJA2dQ9FJvJTFpwxU0410km/int06xBRaxh26TMQEUNXs4x0Sh+Jo77D0NuDLPUApK0q0u4Vp4shgka+poVeB2kZxsqYqXFhbIPli0zG+Xy9k/Xk1u6GJmgLVm19FPXckeBEwqEkckJpMjBREcXA2AC3vAxUItnz0ddDMOxXIpgN40KGKPL31ZZaKgKUiqCJatKT24sIpix5WbDsxLe49a4dkUkRmMP6tfzZuuZYd+F5CkqQVsapoZ/SELURw4Q5QHbgNsBBFlAujut+7UCE+4GoR8MN1l0Q7IjBuK8BDRYPmA2whg8CyCGHaE/XqQgOUSLGU6ZYNowowYpF/EA4Tky8IhzLPoOvHQCO8uQhZi1iQzg+CKs0jZxRxfe9dERUHShf82njAKPL6ycHvHMJzCkKFR9jV2Xlz0htUYnA26se2aOoe2k67Mct13Cuzd81XdFBfY3hK97nHLtUxxx33r4ZBYdypVYkaBGF6FTuF1aNTaAMDVbEHTT8QhfVfnsLypDHYZJTVf/F1mEJBErgTkcqcr7FTWD4UhdYGznzgHSDW44/U1A9EoV2vEZwlBHaK30LGJ4sPtDl5/kBRAjug4o+8I4Xtbrebr5cCHl7o9M+jbmR10t2BbDqJn8J0xhi4t1P2eZEgtIsjso+zn5EbTitpeRorjivaoBlFbzOOoOdbWepohfRO2x0ON3j6vpzXKt1IbZiS5UbwtkJfoju9fQHtgkbwE1gWdnDZae3rD+QDdzVf9U/9L9hxvSO5WFX7ZziuA693T8DL2AEa97eCud9JpUQKi6fs18i7mq60/fur9xU7BmWC0aRiZEqpZHnL/DjFIht2KO4A600Fxu3xcrtarRQb4/PR6Py0smcEYzBqFDIleyEn4YeDo+kOhREF+WTLg5DAaM/gA2RAP/DywKYw6u65erFRC45KZLbwUgRsqfM2bAq35IVS6XQUaYu8IiTYsKVHjKMtNq2Keg1ch3NOl53dgItFUB8XtFkCL1siYoPfU2LCgXvaJMa2Z0QBlg8Gr5DetlVIYq5fvkhf4M89Y69oYQnyADAovKEiqt4qbrQvyAwm/vXHX3/99z9fNi3pDUAnTlj9pV3KntbKRviFlDGn7j+///27ib//uafMbUfh8O2g4vK8v1WgcFEwKfzrd8SfX0KKi3TxdDIoUKUrLgMmsQgtsL0UhvKz2JSFsOpPV3OPZvjFbnKp9E9g0t///teXcPZr0vVyT0UkatMVxuQ9q+wlzIbmJP7/H3/++ecf/0eEaSgm8HTgasZd95VvsD+/b0FGhqgJoi3In2FLYlLVoYvG8zjFTcnrKQZH+jaDcTmvQv1Gqd6tp3y9jDbGjUPBCmFejmv4Hvv7/lLSaP92eXXZbxhhxGF1xNJ1yTLrvu/aA5Aw7YKWtNuZRYnFJEP2ItTcPm/hJF1meihHc0YtpApVW3jRQIKgAk8OPCIG98emLuy+Q/GbqHRrkC0IBXcw9qZ+peHwrDMw3cN6T4lxElkk6VIEk0Yr9gU8goUlm4YeQnulk2S3ZiouAUZ4jj6jnuqioS8yuX+BzyLBtPKlm8aaONvNihtam+yEPejE2mmF85QauUkciitBc9VgN0V239LsGSRISx6Ik3eO7o2j2moDwOl2fJBUoZDRtEzB1hbCnu4EpgW3aoRcG8ePzNHdCmJ6K7j28ioxGRUBAJ+JGzqlelmIIPeo4Ia4dZhDc5EfYaZtKgW8YWsNOoKtJYZVcta244DeVGgLxJ7tzlFrqamd5Bga45/HfNuR1gG34GKJWeNTETNEATNgeDVWwa259NHmxrvxbgChIqZosU2d6bs5HMSkgLWK5wiTwIjVJHY2Rcb5yiqhC3YoZ72oCZN0ueY1QKXgPBQaVzFKgSbvcSlPG4hOK7Nf1iSZM3oey1MqUJ0Q8OLQxokvSYNvzK/i0x4azbmcFPLp3e3iZKpuDDpe6qQR6Q9ObWD+j2EALj67hnB9n/vC0lXv6ExcjSctI69tkrLJXKZcqfm6tgN6dOAYAuMnRHHnRXwyrkw6twQguK2FiWGn3Ru0WpVCgeyNKFxUWoPipOk9EYlFw+EU6o5y5SnOYYweRipgTZcGPg6LBhc51MnnqT1ch0I7C8MIGhvGGhIJ3NDsrjtE3chTGYLKoT30cbZAQIdnMl7P6THBUKTEzf3rfKHLt/AVtz2NthNHs4M+FNv/QGPX37Bm5KiP+vq4Ws/eb693ofAKWPxFJs2/nvUpzqIrHk7DJj6ZiQ8TeeZFit1SjhZNDybkLkvaHZsjhnaqncqg1x6PXJr86oxIn0o1r+WSQIB1rAftwOpW4yiqfTWzuMVE4AYJpmeOFXoGBa18f7Yar0B/vG2GI3zJ7ptI+1+4rW00pjyeMJql4vqsaE7J4sSSc1Syz5m2TtL2FACRVNdOiw/sm+zmU1oK5tZ8SLYwD9zZhNR25DhKvRenYW72G/lgc6QDPFm2kclC8fMpmjYuRxFZV9R2QadxFXtyIXYolZ6Z5kDT72S4G+U5RJUWrkY0yBmuu2rez+gmIUEBxbTt+7p0M8QclDnb/0iH0W4qQoN5f3GdUaY/+Y/ySGKlq80OVL4KanttpxPdoVL0A+5dDZ5U+ZojIxiAuEo8urtCYrdyNwPSOaPsQAnsx00awi489SRxwdAkXeRdvY/+AaMNUssD4Ou5p2OS/so5VAY9GGQHq2eGGE1hE+iR0wYM1tdFV1+D9OdGjnOwBpVXX1evKW+G+jafWq6MmJB3SbLhlgXAugnvYLPPuBTNt+8VCiXqV75kfRRm1xwmoSZ4yu5dI6inGmuInTHrEN/r2t94/Flf02aXo4KjWHLGGOZc4Z0zJ6vZG05/RFRG/UuhBCapFLVkjcMnwEO3/o7OclbWV3Yry6+dyaDSqo3RNCBUeNcgpXAOFz1eocvwE6TqaRCzm7RyI1aOGVVy0Ilj8muADf7vKf8UNlW+TfhXIpsPFqQIqSlKAkNWcKaN8hvm9jaAPlnVF68JesKI41Ip9wtf13wL+jcOJzqnvjUFOYVUjKK/Ygm0PnmbKL755/5RvpuuXY2DE0+zhV/EMF+APsKuMsuuzaWCCmit6lVLfds8Y6A5oyS8Jzi4kdWfV2+z+7vbp/uXt9VCJ/QFk0jFqaNk6nbSsC8s94s86rzWlPXMCZoznBMcvBOpW9g0ffRmCBFYGklzTs4UNoFWeSBrR7gipcp066jDAJpAUxdDc9I0Y4FbICvMIrTA9hl53zaF4aCiF2UqjLpDn9CcM/ZJ9oa8HDeDdwhHJGBX5MsKsztQHIMSBO17sjKmt8GCdE+sJDeKgsuvTnlTSECz3m9xEyjLNyx9PdE9OTBUwg2u4wJdbB9xSGR/MPQJj2xT7cd9DrTifIpXzhCoC5s/xdNHTRh+gRchUFmbjlLcFOpoBLUPQR/N2XOjEXUp4LCfyMADWsSnXhCg3LnB3ZYYSWpCRWl6oLY/wRSC7TYTQaH8DNJU5KmVDIBLeSUDKGRXApjUOvlIbImuDTC7eXvGwOrmnAgfB9DB2P+8vlAIbOwD2vCnKmQO8Ri5AzX2TYEdzIkx4zKMXxsibgLtjPiBdXQ+5xPrIVaCKMTzHg7UyxDZtO9dExhf959kEAtUGYKtgjo/+4BeWt+zFIndzZ44FS+yq0PqfJqjv3TH0lHQiKKQxvcP1RfWKg5uMLKt9BWO8hU2h2iaCq4md2DHLEatfC6X07q0hWFwJDgy8JhHsb49i6D+MHEHMBgKXwMtfjHQONWfghwLSiGcvSKu4IID/5kFknKzIbIbEVmor+F24xGGkm+zqvQgbBnK9JSug1JoGnDlIpUwTYxEC4hg2BQuEkegkAXYcr6Ti2KkcAq5qiP2vgWWfRXHpdT2PmIreJjDN2GCxjoV+HDbjn0AY/VN4BxmocxN7P6x41Kow1FWR+wjDsKUU4GxAdtTh34KD2aY+tEMb5bOlzsaCOQ4Mjhh/ajHaiCFgQUHfpA6kt0Dc6qKcyiy1HkHCpX7qZW/zppQbXDn5UZxWwgqA/J1OxGuy4vlfI1Hqx7xxAKr0FS5uXt//TFbr+er5XJBMDVBUvfMkAmI055YwsuAVzAFwDeWy9V8vX6b/Xh9v3+6SbCVG4dznwIpBMuDKQsiGxJubm6ur68fHh5uGZCSWuW7+eE1wLzni0mygt9l64pcZ1p/FArZIboPbmZIN6lJcK+4b3P/9yNQKBZHpPB0++giYHg2xkKvI0oaDDFmclreuGgVa+3xKMour8uz82ajVxxUCka3ruVIEDENJB5RH8K2Lk4YJZlKl3KaVq9nMpk8gHQCz9NW1aN8hqBer2taLldKb+o6BK7ogRJsPEC9bphj3iDNEWZZQfn4Ee3SAXl+mARfMyyFEPs6om8BacUwG1dOQ1KIkfYjnuADQeLfQnwhLIWY+Tn2CT5heqiEpfBQp04EApkoRBglLIWwDI56riRQGMJBbYekEIR14B7yQ2AcUl0AhSG6dUhhZW/sqIRcJyEp1I4tSsOfx9YIRyHYQKI3pG8Glg7vXksQksKrsBaFABTDKSywaXbeGIlr4IjxYAJ6xM6ut8Ok7NolADfKHaoUIxDoBO9o/dNyhx1/GovYj35CL92xuhsr0R0au0UHaX3L/kOLCzRluovat4+E38EKStMtOcc/CfwkSVvo1LYW9jAbULZ5fEmrZcNBD3MPgr1ztl3eJFMzrrDVhibHyZxhb5M5qsHmgDlX6GxS6Oa8UYlkSjN6vjKOy0k1X0olnZNskqm0Vq4W2ZZRR1aFDnKejt/K2fi0PZnUarVJo90cua5mPI0X+6POeDzudEacSpYPwaKIZM0/PC5IL60cryqHg7MPIGQY1HcKDlMvxNcAjYPOEZOGAdh4qjRgYAuiEqfyiMVp4TClz+GRKUw63PPahs2WxybQCo1zf27jstMYlI9YerETkqlc3qgWKoOiiUGlUDXyPulq31qqd8twyr1hlPPaxtjwJz7xiU984hPC8D8xioUM56Xi2AAAAABJRU5ErkJggg==");
}

```

**Comment by yesoreyeram** [comment]
# Neon Theme

![image](https://user-images.githubusercontent.com/153843/56898625-693a4100-6a89-11e9-8a63-0bdb11c4a131.png)

https://github.com/yesoreyeram/grafana-themes/blob/master/themes/neon.css

**Comment by yesoreyeram** [comment]
# v0.0.2

Edtior UI 

![image](https://user-images.githubusercontent.com/153843/56966143-76713180-6b56-11e9-8979-4eab634b943f.png)

Theme Picker 

![image](https://user-images.githubusercontent.com/153843/56966188-88eb6b00-6b56-11e9-935a-f493b88c5175.png)

**Comment by yesoreyeram** [comment]
# v0.0.3

![image](https://user-images.githubusercontent.com/153843/57007587-a87ba580-6be1-11e9-8a2e-a1d571ae59d6.png)

![image](https://user-images.githubusercontent.com/153843/57007597-c0ebc000-6be1-11e9-9293-70def425ea66.png)

**Comment by yesoreyeram** [comment]
# v0.0.4

![image](https://user-images.githubusercontent.com/153843/57070256-ba874200-6cce-11e9-85f5-e0a036eb306b.png)

![image](https://user-images.githubusercontent.com/153843/57070201-99265600-6cce-11e9-9a9c-734121df7cb8.png)

**Comment by yesoreyeram** [comment]
# v0.1.0

![image](https://user-images.githubusercontent.com/153843/57117976-e7cc0280-6d57-11e9-895c-da1d1fdfd9a0.png)

![image](https://user-images.githubusercontent.com/153843/57117982-f61a1e80-6d57-11e9-8150-c97ae7b3bbc5.png)

**Comment by yesoreyeram** [comment]
# Steps

![image](https://user-images.githubusercontent.com/153843/57118255-177c0a00-6d5a-11e9-8456-a9231914690d.png)

![image](https://user-images.githubusercontent.com/153843/57118263-24006280-6d5a-11e9-9eae-9c4d8669c2d7.png)

![image](https://user-images.githubusercontent.com/153843/57118273-2fec2480-6d5a-11e9-88db-e23608b6eea2.png)

![image](https://user-images.githubusercontent.com/153843/57118285-3bd7e680-6d5a-11e9-89c3-bab11c5a6d9f.png)

![image](https://user-images.githubusercontent.com/153843/57118300-47c3a880-6d5a-11e9-97ab-573cfd7f0999.png)

![image](https://user-images.githubusercontent.com/153843/57118307-501be380-6d5a-11e9-8378-874a6be81463.png)

![image](https://user-images.githubusercontent.com/153843/57118315-5e69ff80-6d5a-11e9-96e8-9ba79996d42c.png)

![image](https://user-images.githubusercontent.com/153843/57118328-69bd2b00-6d5a-11e9-9d18-b57db79fef79.png)

![image](https://user-images.githubusercontent.com/153843/57118339-7ccffb00-6d5a-11e9-80ae-c8d1d46bb121.png)

**Comment by yesoreyeram** [comment]
# Steps to add new Theme option

Click "Add theme" button
![image](https://user-images.githubusercontent.com/153843/57118617-65920d00-6d5c-11e9-8f38-0572dcdb75e0.png)

Give your theme a name.. Say "London"
![image](https://user-images.githubusercontent.com/153843/57118605-53b06a00-6d5c-11e9-9af5-2719b30630e7.png)

Add the image URL of your choice. In my case, i got the image url from unsplash..
![image](https://user-images.githubusercontent.com/153843/57118642-907c6100-6d5c-11e9-9a9b-e7f3fd8426ce.png)

Copy other theme styles from previous theme ( In my case, I copied the style from "night theme" and ajusted background color (0,0,0,0.3) to (0,0,0,0.8) to align with image )

![image](https://user-images.githubusercontent.com/153843/57118673-db967400-6d5c-11e9-8a60-7656971d0ac8.png)

Go back to view mode..
![image](https://user-images.githubusercontent.com/153843/57118731-36c86680-6d5d-11e9-83a9-c71ab9275b50.png)

Optionally click "Apply as default theme" button to make this theme as default for this dashboard

![image](https://user-images.githubusercontent.com/153843/57118778-74c58a80-6d5d-11e9-80d1-0d1c3d5a5866.png)



You are done..

**Comment by javobarra** [comment]
amazing! @yesoreyeram ! Congrulats.

Is it possible to add a local image to the background?? (not using url like unplash)
I don't know where is the correct directory to put the image for do that.

Can you help me??? Thanks

**Comment by ngehani** [comment]
Nicely done!

@yesoreyeram - Are you up for customizing our Grafana to our own visual theme?

**Comment by yesoreyeram** [comment]
## New grafana version's theme in older grafana.

If you are using older version of grafana, and want to use new version of grafana's theme without upgrading, you can use the following trick.

use grafana new version's css from some where like play.grafana.org . example `https://play.grafana.org/public/build/grafana.dark.140a71a213168ab01b3a.css` and use the css as external stylesheet in boom theme panel.

NOTE : Though this works, there may be breaking changes which are not known. 

With default grafana 6 theme
![image](https://user-images.githubusercontent.com/153843/90173512-72ddda00-dd9c-11ea-9c23-85f68fdbe552.png)

with grafana 7 theme selected in grafana 6
![image](https://user-images.githubusercontent.com/153843/90173568-8d17b800-dd9c-11ea-8152-030080ed5dc2.png)

using the following setup
![image](https://user-images.githubusercontent.com/153843/90173608-9e60c480-dd9c-11ea-8f17-01c019695fed.png)

**Comment by yesoreyeram** [comment]
Version 7

![image](https://user-images.githubusercontent.com/153843/99795058-0e60b280-2b23-11eb-88fb-fa673a6111ea.png)

![image](https://user-images.githubusercontent.com/153843/99795201-45cf5f00-2b23-11eb-8da7-e6dcb4383c7f.png)

**Comment by yesoreyeram** [comment]
## version 2.0 Screenshots

![image](https://user-images.githubusercontent.com/153843/99880461-5e1aa900-2c0b-11eb-9c28-3c80381f2504.png)
![image](https://user-images.githubusercontent.com/153843/99880482-80142b80-2c0b-11eb-938c-d28c7b59058a.png
![image](https://user-images.githubusercontent.com/153843/99880502-a20dae00-2c0b-11eb-8355-c7c87bcb2f5c.png))
