### ISSUE TITLE
Transparency Broken

### ISSUE THREAD

**Issue by GideonWolfe** [yesoreyeram/yesoreyeram-boomtheme-panel#14]
I originally opened an [issue](https://github.com/grafana/grafana/issues/22985) in the grafana repo, but was told it was a boom theme issue.

I use boom theme to set the background to pitch black image.

Here is what it should look like

![](https://gideonwolfe.com/img/sysadmin/TIG/dockerstats.png)

Here is what it currently looks like:

![DeepinScreenshot_select-area_20200323143026](https://user-images.githubusercontent.com/32942052/77365164-e0686b80-6d12-11ea-8066-3689d44c2973.png)

**Comment by GideonWolfe** [comment]
Turns out a random FF plugin was at fault

**Comment by GideonWolfe** [comment]
Ok it seems like turning [DarkReader](https://github.com/darkreader/darkreader) off gets rid of the borders, but only if the following custom CSS is active

```css
.panel-container {
  background: transparent;
}
```

**Comment by yesoreyeram** [comment]
So, it sounds like a behavior of darkreader. I don't think boom theme plays anything here.

**Comment by yesoreyeram** [comment]
After #30 react migration, panel transparency is now respected. Feel free to reopen if the issue still exist with the new release ( available in release page )
