### ISSUE TITLE
Background Picture Carousel

### ISSUE THREAD

**Issue by ajaywazir** [yesoreyeram/yesoreyeram-boomtheme-panel#6]
Hi
I saw your boomtheme plugin for grafana.
It seems I can add more than 1 background picture but only one is displayed.
Is it possible to make the pictures cycle (say in 5 seconds).

Ajay

**Comment by yesoreyeram** [comment]
I don't think this can be supported anytime soon. Carousel implementation deserves separate plugin. I am closing this unless community comes with different idea.
