### ISSUE TITLE
[Help Required] How to set default theme to a boom customized one?

### ISSUE THREAD

**Issue by ken-cogniac** [yesoreyeram/yesoreyeram-boomtheme-panel#70]
I created a few themes with boom, but i can't configure it to be the default one. I will have to manually switch the theme. Any way to set default theme to a boom customized one? Any parameters i can use in the dashboard json model? Thanks.

**Comment by MrFiestaxxl** [comment]
You can set this per Panel. 
<img width="666" alt="Bildschirmfoto 2023-05-22 um 08 25 12" src="https://github.com/yesoreyeram/yesoreyeram-boomtheme-panel/assets/25901511/77a86824-8e1d-4199-a960-ff31c8553093">

Use the name you gave the Theme.

**Comment by ken-cogniac** [comment]
thanks. it works perfectly
